### ISSUE TITLE
Arrange Library and Bundle settings

### ISSUE THREAD

**Issue by renedelima** [acsiomatic/device-detector-bundle#30]
Create separate sections for `DeviceDetector` and `DeviceDetectorBundle` itself in the configuration file.

**Comment by renanbr** [comment]
```yaml
# config/packages/acsiomatic_device_detector.yaml

acsiomatic_device_detector:

    device_detector:

        # If true, DeviceDetector will trigger parser() when necessary
        auto_parse: true

        # Version truncation behavior, it may assume: major, minor, patch, build, or none
        # By default minor versions will be returned (e.g. X.Y)
        version_truncation: 'minor'

        cache:

            # If null, it will disable caching
            pool: 'cache.app'

        bot:

            # If true getBot() will only return true if a bot was detected (speeds up detection a bit)
            discard_information: false

            # If true, bot detection will completely be skipped (bots will be detected as regular devices then)
            skip_detection: false

    symfony:

        twig:

            # If null, it will not assign Twig variable
            variable_name: 'device'

        routing:

            # If null, it will not tag DeviceDetector as routing condition service
            condition_service_alias: 'device'
```
